/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { SpotExchange, SpotExchangeInterface } from "../SpotExchange";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_orderBook",
        type: "address",
      },
      {
        internalType: "address",
        name: "_vault",
        type: "address",
      },
      {
        internalType: "address",
        name: "_feeRecipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_feeBps",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "buyOrderId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "sellOrderId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "matchAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "matchPrice",
        type: "uint256",
      },
    ],
    name: "executeMatch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_matcher",
        type: "address",
      },
    ],
    name: "setMatcher",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_feeBps",
        type: "uint256",
      },
    ],
    name: "setFeeBps",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_recipient",
        type: "address",
      },
    ],
    name: "setFeeRecipient",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getFeeBps",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class SpotExchange__factory {
  static readonly abi = _abi;
  static createInterface(): SpotExchangeInterface {
    return new Interface(_abi) as SpotExchangeInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): SpotExchange {
    return new Contract(address, _abi, runner) as unknown as SpotExchange;
  }
}
