/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ISpotOrderBook {
  export type OrderStruct = {
    id: BigNumberish;
    user: AddressLike;
    base: AddressLike;
    quote: AddressLike;
    price: BigNumberish;
    amount: BigNumberish;
    isBuy: boolean;
    active: boolean;
  };

  export type OrderStructOutput = [
    id: bigint,
    user: string,
    base: string,
    quote: string,
    price: bigint,
    amount: bigint,
    isBuy: boolean,
    active: boolean
  ] & {
    id: bigint;
    user: string;
    base: string;
    quote: string;
    price: bigint;
    amount: bigint;
    isBuy: boolean;
    active: boolean;
  };
}

export interface SpotOrderBookInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "nextOrderId"
      | "setExchange"
      | "createOrder"
      | "cancelOrder"
      | "reduceOrderAmount"
      | "getUserOrders"
      | "getOrder"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "nextOrderId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setExchange",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createOrder",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reduceOrderAmount",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserOrders",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrder",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "nextOrderId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExchange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reduceOrderAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOrder", data: BytesLike): Result;
}

export interface SpotOrderBook extends BaseContract {
  connect(runner?: ContractRunner | null): SpotOrderBook;
  waitForDeployment(): Promise<this>;

  interface: SpotOrderBookInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  nextOrderId: TypedContractMethod<[], [bigint], "view">;

  setExchange: TypedContractMethod<
    [_exchange: AddressLike],
    [void],
    "nonpayable"
  >;

  createOrder: TypedContractMethod<
    [
      base: AddressLike,
      quote: AddressLike,
      price: BigNumberish,
      amount: BigNumberish,
      isBuy: boolean
    ],
    [bigint],
    "nonpayable"
  >;

  cancelOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  reduceOrderAmount: TypedContractMethod<
    [orderId: BigNumberish, filledAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getUserOrders: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  getOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [ISpotOrderBook.OrderStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "nextOrderId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setExchange"
  ): TypedContractMethod<[_exchange: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createOrder"
  ): TypedContractMethod<
    [
      base: AddressLike,
      quote: AddressLike,
      price: BigNumberish,
      amount: BigNumberish,
      isBuy: boolean
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelOrder"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reduceOrderAmount"
  ): TypedContractMethod<
    [orderId: BigNumberish, filledAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getUserOrders"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getOrder"
  ): TypedContractMethod<
    [orderId: BigNumberish],
    [ISpotOrderBook.OrderStructOutput],
    "view"
  >;

  filters: {};
}
